# Generated by Django 5.0.1 on 2024-02-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('admission_date', models.DateField()),
                ('attending_physician', models.CharField(max_length=50)),
                ('attending_nurse', models.CharField(max_length=50)),
                ('emergency_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.emergency')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.BooleanField(default=False)),
                ('Bed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.bed')),
            ],
        ),
    ]
