# Generated by Django 5.0.1 on 2024-02-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='clean',
        ),
    ]
