# Generated by Django 5.0.1 on 2024-02-03 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='status',
            new_name='clean_status',
        ),
        migrations.AlterField(
            model_name='bed',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.patient'),
        ),
        migrations.AlterField(
            model_name='room',
            name='Bed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.bed'),
        ),
    ]
