# Generated by Django 5.0.1 on 2024-02-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_rename_status_room_clean_status_alter_bed_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(null=True),
        ),
    ]
