# Generated by Django 5.0.1 on 2024-02-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_patient_medical_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Bed',
            new_name='bed',
        ),
    ]
