# Generated by Django 5.0.1 on 2024-02-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_remove_room_bed_room_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bed',
            field=models.ManyToManyField(blank=True, to='room.bed'),
        ),
    ]
