# Generated by Django 5.0.1 on 2024-02-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_remove_room_bed_bed_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
    ]
