# Generated by Django 5.0.1 on 2024-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_bed_bed_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
