# Generated by Django 5.0.1 on 2024-02-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_patient_age_alter_bed_patient_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='name',
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='take',
            field=models.CharField(choices=[('after', 'After Meal'), ('before', 'Before Meal')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='timing',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
