# Generated by Django 5.0.1 on 2024-02-04 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_rename_patient_medication_patient_medication_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medication',
            name='medication_name',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='price',
        ),
        migrations.AddField(
            model_name='medication',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.medicine'),
        ),
    ]
