# Generated by Django 5.0.1 on 2024-02-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_medicine_remove_medication_medication_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
