# Generated by Django 5.0.1 on 2024-02-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_alter_medication_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('MRI', 'MRI'), ('Blood Test', 'Blood Test')], max_length=50)),
            ],
        ),
    ]
