# Generated by Django 5.0.1 on 2024-02-04 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.patient'),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
