# Generated by Django 5.0.1 on 2024-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0021_test_patient_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discharge',
            field=models.BooleanField(default=False),
        ),
    ]
