# Generated by Django 5.0.1 on 2024-02-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0023_test_test_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_bill',
            new_name='bill',
        ),
    ]
