# Generated by Django 5.0.1 on 2024-02-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0026_alter_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_img',
            field=models.ImageField(blank=True, null=True, upload_to='room'),
        ),
    ]
