# Generated by Django 5.0.1 on 2024-02-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0027_room_room_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FileField(upload_to='bill')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.patient')),
            ],
        ),
    ]
